#!/usr/bin/env python3

from tinyunit.client import *

class SetupTeardownTests(TestCase):

    def __init__(self):
        super(SetupTeardownTests,self).__init__()
        self._value = 42

    def setup(self):
        self._value = 43

    def teardown(self):
        del self._value

    @testmethod
    def testSetup(self):
        self.assertEquals(self._value,43)

if __name__=="__main__":
    run()

